# Generated by Django 4.2.13 on 2024-06-11 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='create_at',
            new_name='crate_at',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='cpation',
            new_name='caption',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='create_at',
            new_name='crate_at',
        ),
    ]
