# Generated by Django 4.2.13 on 2024-06-12 16:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0002_rename_create_at_comment_crate_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='crate_at',
            new_name='create_at',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='crate_at',
            new_name='create_at',
        ),
        migrations.AlterField(
            model_name='post',
            name='caption',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_likes',
            field=models.ManyToManyField(blank=True, related_name='post_image_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
