# Generated by Django 4.2.13 on 2024-06-12 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_rename_crate_at_comment_create_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='caption',
            new_name='cpation',
        ),
    ]
