# Generated by Django 4.2.13 on 2024-06-12 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_rename_caption_post_cpation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='cpation',
            new_name='caption',
        ),
    ]
